config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard'

  shallow do
    resources :shifts, only: %i[index new create destroy edit update]
    resources :restaurants, only: %i[new create show destroy] do
      resources :workers do
        resources :skills
      end
      get '/report', to: 'reports#show'
      get '/shifts', to: 'shifts#index'
      resources :stations, except: [:show]
      resources :floorplans
      resources :reports, except: [:show]
      resources :notes, only: %i[new edit create update destroy]
    end
  end

  # get '/restaurant/:restaurant_id/layout', to: 'restaurants#layout', as: 'restaurant_layout'
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :skills, dependent: :destroy
  has_many :workers, through: :skills
  belongs_to :restaurant
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :get_restaurant
  def index
    @stations = policy_scope(Station)
  end

  def new
    @station = Station.new()
    authorize @station
  end

  def create
    @station = Station.new(station_params)
    @station.restaurant = @restaurant
    @station.save
    authorize @station
    redirect_to(restaurant_stations_path(@restaurant))
  end

  def edit
    @station = Station.find(params[:id])
    authorize @station
  end

  def update
    @station = Station.find(params[:id])
    @station.update(station_params)
    @station.save
    authorize @station
    redirect_to(restaurant_stations_path(@restaurant))
  end

  def destroy
    @station = Station.find(params[:id])
    @station.destroy
    authorize @station
    redirect_to(restaurant_stations_path(@restaurant))
  end

  private

  def get_restaurant
    @restaurant = current_user.restaurant
  end

  def station_params
    params.require(:station).permit(:name)
  end
end

app/views/stations/edit.html.erb
<div class="container-fluid d-flex flex-row p-0">
  <%= render "shared/sidebar"%>
  <section class="dashboard justify-between d-flex flex-column">
    <div class="dashboard-card flex-grow-1">
      <div class="dashboard-header d-flex justify-content-between">
        <div>
        <h2 class="page-title"><%= @restaurant.name %></h2>
        <h4>Layout</h4>
        </div>
        <h6 class="page-title">Dashboard/Settings/Layout/Edit</h6>
      </div>
      <div class="card-body p-1">
        <%= simple_form_for @station do |f| %>
          <%= f.input :name %>
          <%= f.submit class: "btn btn-outline-success rounded-pill" %>
        <% end %>

      </div>
    </div>
  </section>
</div>

app/views/stations/index.html.erb
<div class="container-fluid d-flex flex-row p-0">
  <%= render "shared/sidebar"%>
  <section class="dashboard justify-between d-flex flex-column">
    <div class="dashboard-card flex-grow-1">
      <div class="dashboard-header d-flex justify-content-between">
        <div>
        <h2 class="page-title"><%= @restaurant.name %></h2>
        <h4>Layout</h4>
        </div>
        <h6 class="page-title">Dashboard/Settings/Layout</h6>
      </div>
      <div class="card-body p-1">
      <div class="d-flex justify-content-end">
        <%= link_to '+ New station', new_restaurant_station_path(@restaurant),class:"btn btn-primary rounded-pill m-2" , style: "color: white; text-decoration: none" %>
      </div>
        <% @stations.each do |station| %>
          <div class="dashboard-card d-flex justify-content-between text-center align-items-center p-2 flex-grow-1">
            <h4 class="m-0">
              <%= station.name %>
            </h4>
            <div class="col-3 d-flex justify-content-end">
              <%= link_to 'Edit', edit_station_path(station), class: "btn btn-table btn-outline-warning rounded-pill m-1 mt-0 mb-0" %>
              <%= link_to 'X', station_path(station), class: "btn btn-table btn-outline-danger rounded-pill m-1 mt-0 mb-0", method: :delete %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/stations/new.html.erb
<%= simple_form_for [@restaurant, @station] do |f| %>
  <%= f.input 'name' %>
  <%= f.submit %>
<% end %>