config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard'

  shallow do
    resources :shifts, only: %i[index new create destroy edit update]
    resources :restaurants, only: %i[new create show destroy] do
      resources :workers do
        resources :skills
      end
      get '/report', to: 'reports#show'
      get '/shifts', to: 'shifts#index'
      resources :stations, except: [:show]
      resources :floorplans
      resources :reports, except: [:show]
      resources :notes, only: %i[new edit create update destroy]
    end
  end

  # get '/restaurant/:restaurant_id/layout', to: 'restaurants#layout', as: 'restaurant_layout'
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :report
  belongs_to :worker
  belongs_to :restaurant
  validates :start, presence: true
  validates :finish, presence: true
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def index
    @shifts = policy_scope(Shift)
    respond_to do |format|
      format.json {
        render json: @shifts
      }
      format.html {
        render json: @shifts
      }
    end
  end

  def new
    @shift = Shift.new()
    authorize @shift
  end

  def edit
    @shift = Shift.find(params[:id])
    authorize @shift
  end

  def update
    @shift = Shift.find(params[:id])
    @shift.update({:start=>shift_params[:start], :finish=>shift_params[:finish]})
    authorize @shift
    @shift.save
    redirect_to restaurant_report_path(@shift.restaurant)
  end

  def create
    @shift = Shift.new({:start=>shift_params[:start], :finish=>shift_params[:finish]})
    worker = set_worker(nil, params[:shift]["first_name"], params[:shift]["last_name"])
    @shift.worker = worker
    @restaurant = current_user.restaurant
    @shift.restaurant = @restaurant
    create_report if @shift.restaurant.report.nil?
    @shift.report = @shift.restaurant.report
    authorize @shift
    if @shift.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.append(:shifts, partial: "shifts/shift", locals: { shift: @shift })
      end
      format.html { redirect_to restaurant_report_url(@restaurant) }
    end
    else
      render 'new'
    end
  end

  def destroy
    @shift = Shift.find(params[:id])
    @shift.destroy
    authorize @shift
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@shift) }
      format.html         { redirect_to restaurant_report_url(@restaurant) }
    end
  end

  private

  def shift_params
    params.require(:shift).permit(:start, :finish, :first_name, :last_name) do |p|
      p[:start] = Time.parse(p[:start])
      p[:finish] = Time.parse(p[:finish])
    end
  end

  def create_report
    report = Report.new
    report.restaurant = current_user.restaurant
    report.save
  end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/shifts/_form.html.erb
<%= simple_form_for(@shift) do |f| %>
  <div class="row align-items-center">
    <input type="text" name="shift[first_name]" placeholder=<%= @shift.worker.present? ? @shift.worker.first_name : 'First name' %> class="col-2 p-1 m-1">
    <input type="text" name="shift[last_name]" placeholder=<%= @shift.worker.present? ? @shift.worker.last_name : 'Last name' %> class="col-3 p-1 m-1">
    <div class="col"></div>
    <div class="col divisor string require start">
      <input class="form-control string required" type="time" name="shift[start]" id="shift_start" value=<%= @shift.start.nil? ? '' : "#{@shift.start.hour}:#{@shift.start.min}" %>>
    </div>
    <div class="col string require finish">
      <input class="form-control string required" type="time" name="shift[finish]" id="shift_finish" value=<%= @shift.finish.nil? ? '' : "#{@shift.finish.hour}:#{@shift.finish.min}" %>>
    </div>
    <div class="col">
      <%= f.submit 'Save', class:"btn btn-success col-6 m-1" %>
      <%= link_to 'Back', restaurant_reports_path(current_user.restaurant), class:"btn btn-secondary col-4" %>
    </div>
  </div>
<% end %>

app/views/shifts/_shift.html.erb
<%= turbo_frame_tag dom_id(shift), class:"table-data row text-center align-items-center p-1" do %>
  <div class="cell col text-start"><%= shift.worker.number %></div>
  <div class="cell col-4 text-start"><%= "#{shift.worker.first_name} #{shift.worker.last_name}" %></div>
  <div class="cell col divisor starting-time"><%= shift.start.strftime("%d/%b %H:%M") %></div>
  <div class="cell col finishing-time"><%= shift.finish.strftime("%d/%b %H:%M") %></div>
  <div class="cell col-2 d-flex align-items-center justify-content-center">
    <%= link_to 'Edit', edit_shift_path(shift), class: "btn btn-table btn-outline-warning rounded-pill m-1 mt-0 mb-0" %>
    <%= link_to 'X', shift_path(shift), class: "btn btn-table btn-outline-danger rounded-pill m-1", method: :delete %>
  </div>
<% end %>

app/views/shifts/edit.html.erb
<%= turbo_frame_tag @shift do %>
  <%= simple_form_for(@shift) do |f| %>
  <div class="row align-items-center">
    <input type="text" name="shift[first_name]" placeholder=<%= @shift.worker.first_name %> class="col-2 p-1 m-1">
    <input type="text" name="shift[last_name]" placeholder=<%= @shift.worker.last_name %> class="col-3 p-1 m-1">
    <div class="col"></div>
    <div class="col divisor string require start">
      <input class="form-control string required" type="time" name="shift[start]" id="shift_start" value=<%= "#{@shift.start.strftime("%H")}:#{@shift.start.strftime("%M")}" %>>
    </div>
    <div class="col string require finish">
      <input class="form-control string required" type="time" name="shift[finish]" id="shift_finish" value=<%="#{@shift.finish.strftime("%H")}:#{@shift.finish.strftime("%M")}" %>>
    </div>
    <div class="col">
      <%= f.submit 'Save', class:"btn btn-success col-6 m-1", id: 'save' %>
      <%= link_to 'Back', restaurant_report_path(current_user.restaurant), class:"btn btn-secondary col-4" %>
    </div>
  </div>
<% end %>

<% end %>

app/views/shifts/new.html.erb
<%= turbo_frame_tag 'new' do %>
  <%= simple_form_for(@shift) do |f| %>
  <div class="row align-items-top p-2">
    <div class="col-2">
      <input type="text" name="shift[first_name]" placeholder='First name' class="col-12">
    </div>
    <div class="col-3">
      <input type="text" name="shift[last_name]" placeholder='Last name' class="col-12">
    </div>
    <div class="col divisor string require start d-flex flex-column">
      <input class="form-control string required" type="time" name="shift[start]" id="shift_start">
    <% if @shift.errors.include?(:start) %>
        <p class="error-message m-0 p-0">When do we start?</p>
    <% end %>
    </div>
    <div class="col string require finish">
      <input class="form-control string required" type="time" name="shift[finish]" id="shift_finish">
      <% if @shift.errors.include?(:finish) %>
        <p class="error-message m-0 p-0">When do we finish?</p>
      <% end %>
    </div>
    <div class="col-3">
      <%= f.submit 'Add', class: "btn btn-success col-6", id: "save" %>
      <%= link_to 'Back', restaurant_report_path(current_user.restaurant), class:"btn btn-secondary col-4" %>
    </div>
  </div>
<% end %>
<% end %>