config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard'

  shallow do
    resources :shifts, only: %i[index new create destroy edit update]
    resources :restaurants, only: %i[new create show destroy] do
      resources :workers do
        resources :skills
      end
      get '/report', to: 'reports#show'
      get '/shifts', to: 'shifts#index'
      resources :stations, except: [:show]
      resources :floorplans
      resources :reports, except: [:show]
      resources :notes, only: %i[new edit create update destroy]
    end
  end

  # get '/restaurant/:restaurant_id/layout', to: 'restaurants#layout', as: 'restaurant_layout'
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_one :report, dependent: :destroy
  has_many :workers, dependent: :destroy
  has_many :floorplans, dependent: :destroy
  has_many :stations, dependent: :destroy
  has_many :notes, dependent: :destroy
  validates :user_id, uniqueness: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[destroy show]
  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def show
    if @restaurant
      @workers = @restaurant.workers
      authorize @restaurant
    else
      @restaurant = Restaurant.new()
      authorize @restaurant
      redirect_to '/dashboard'
    end

  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    @restaurant.save
    authorize @restaurant
    redirect_to '/dashboard'
  end

  def destroy
    if @restaurant
    authorize @restaurant
    @restaurant.destroy
    authorize @restaurant
    end
    redirect_to '/dashboard'
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end

  def set_restaurant
    @restaurant = current_user.restaurant
  end
end

app/views/restaurants/new.html.erb
<div class="container create-form col-12 col-lg-4 rounded border shadow p-4 mt-4 d-flex flex-column">
  <h2 class="container-title mb-4 p-4">
    Create your restaurant...
  </h2>
  <div class="form p-4 mb-5">
    <%= simple_form_for @restaurant do |f| %>
    <%= f.input 'name',
                label: false,
                placeholder: 'What\'s it called?' %>
    <%= f.submit 'Do it!', class: 'btn btn-primary col-12 mt-5 fs-2 rounded-pill' %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container-fluid d-flex flex-row p-0">
  <%= render "shared/sidebar"%>
  <section class="dashboard justify-between d-flex flex-column">
    <div class="dashboard-card flex-grow-1">
      <div class="dashboard-header d-flex justify-content-between">
        <h2 class="page-title"><%= @restaurant.name %></h2>
        <h6 class="page-title">Dashboard/Settings</h6>
      </div>
      <div class="card-body">
        <%= link_to restaurant_stations_path(@restaurant), class: "btn settings-card dashboard-card " do  %>
          <div class="settings-text" style="color: white; text-decoration: none;">
            Layout
          </div>
        <% end %>
        <%= link_to restaurant_workers_path(@restaurant), class: "btn settings-card dashboard-card " do  %>
          <div class="settings-text" style="color: white; text-decoration: none;">
            Team
          </div>
        <% end %>
        <%= link_to restaurant_floorplans_path(@restaurant), class: "btn settings-card dashboard-card " do  %>
          <div class="settings-text" style="color: white; text-decoration: none;">
            Floorplan
          </div>
        <% end %>
        <%= link_to restaurant_path(@restaurant), method: :delete, class: "btn settings-card dashboard-card " do  %>
          <div class="settings-text" style="color: white; text-decoration: none;">
            Delete restaurant
          </div>
        <% end %>
        </div>
    </div>
  </section>
</div>