config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/dashboard', to: 'pages#dashboard'

  shallow do
    resources :shifts, only: %i[index new create destroy edit update]
    resources :restaurants, only: %i[new create show destroy] do
      resources :workers do
        resources :skills
      end
      get '/report', to: 'reports#show'
      get '/shifts', to: 'shifts#index'
      resources :stations, except: [:show]
      resources :floorplans
      resources :reports, except: [:show]
      resources :notes, only: %i[new edit create update destroy]
    end
  end

  # get '/restaurant/:restaurant_id/layout', to: 'restaurants#layout', as: 'restaurant_layout'
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :restaurant
  has_many :shift, dependent: :delete_all
  has_many :skills, dependent: :destroy
  has_many :stations, through: :skills

  def to_label
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :get_restaurant
  def index
    @workers = policy_scope(Worker)
  end

  def new
    @worker = Worker.new()
    authorize @worker
  end

  def show
    @worker = Worker.find(params[:id])
    authorize @worker
  end

  def edit
    @worker = Worker.find(params[:id])
    authorize @worker
  end

  def create
    @worker = Worker.new(worker_params)
    @worker.restaurant = current_user.restaurant
    @worker.save
    authorize @worker
    redirect_to restaurant_workers_path(@restaurant)
  end

  def update
    @worker = Worker.find(params[:id])
    @worker.update(worker_params)
    @worker.save
    authorize @worker
    redirect_to restaurant_workers_path(@restaurant)
  end

  def destroy
    @worker = Worker.find(params[:id])
    @worker.destroy
    authorize @worker
    redirect_to restaurant_workers_path(@restaurant)

  end

  private

  def get_restaurant
    @restaurant = current_user.restaurant
  end

  def worker_params
    params.require(:worker).permit(:first_name, :last_name, :number)
  end
end

app/views/workers/edit.html.erb
<%= simple_form_for @worker do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :number %>
  <%= f.submit %>
<% end %>

app/views/workers/index.html.erb
<div class="container-fluid d-flex flex-row p-0">
  <%= render "shared/sidebar"%>
  <section class="dashboard justify-between d-flex flex-column">
    <div class="dashboard-card flex-grow-1">
      <div class="dashboard-header d-flex justify-content-between">
        <div>
        <h2 class="page-title"><%= @restaurant.name %></h2>
        <h4>Workers</h4>
        </div>
        <h6 class="page-title">Dashboard/Settings/Workers</h6>
      </div>
      <div class="card-body p-1">
      <div class="d-flex justify-content-end">
        <%= link_to '+ New worker', new_restaurant_worker_path(@restaurant),class:"btn btn-primary rounded-pill m-2" , style: "color: white; text-decoration: none" %>
      </div>
        <% @workers.each do |worker| %>
          <div class="dashboard-card d-flex justify-content-between text-center align-items-center p-2 flex-grow-1">
            <h4 class="m-0">
              <%= worker.first_name %> <%= worker.last_name %>
            </h4>
            <div class="col-3 d-flex justify-content-end">
              <%= link_to 'Stations', worker_path(worker), class: "btn btn-table btn-outline-secondary rounded-pill m-1 mt-0 mb-0" %>
              <%= link_to 'Edit', edit_worker_path(worker), class: "btn btn-table btn-outline-warning rounded-pill m-1 mt-0 mb-0" %>
              <%= link_to 'X', worker_path(worker), class: "btn btn-table btn-outline-danger rounded-pill m-1 mt-0 mb-0", method: :delete %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/workers/new.html.erb
<%= simple_form_for [@restaurant, @worker] do |f| %>
<%= f.input :first_name %>
<%= f.input :last_name %>
<%= f.input :number %>
<%= f.submit %>
<% end %>

app/views/workers/show.html.erb
<h2><%= @restaurant.name %></h2>
<h3><%= @worker.first_name %> <%= @worker.last_name %></h3>
<%= link_to 'Edit Worker', edit_worker_path(@worker) %>
<h3>Stations</h3>
<% @worker.skills.each do |skill| %>
  <p>•<%= skill.station.name %> - <%= skill.level %>/5 - <%= link_to 'Edit', edit_skill_path(skill), class: 'btn btn-outline-primary' %> - <%= link_to '🗑️', skill_path(skill), method: :delete %></p>
<% end %>

<%= link_to '+Add a skill', new_worker_skill_path(@worker), class: 'btn btn-outline-warning' %>